# Generated by Django 3.2.5 on 2021-07-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_monitoring', '0002_disks_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disks',
            name='current_read_speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='disks',
            name='current_write_speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='disks',
            name='free',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='disks',
            name='size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='disks',
            name='used',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ram',
            name='percent_used',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ram',
            name='used',
            field=models.FloatField(),
        ),
    ]
