# Generated by Django 3.2.5 on 2021-07-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_monitoring', '0003_auto_20210708_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='frequency',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='percent_usage',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disks',
            name='current_read_speed',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disks',
            name='current_write_speed',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disks',
            name='free',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disks',
            name='percent_used',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disks',
            name='size',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disks',
            name='used',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ram',
            name='percent_used',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ram',
            name='used',
            field=models.FloatField(max_length=50),
        ),
    ]
