# Generated by Django 3.2.5 on 2021-07-08 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_monitoring', '0005_auto_20210708_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disks',
            name='current_read_speed',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='disks',
            name='current_write_speed',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='disks',
            name='free',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='disks',
            name='size',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='disks',
            name='used',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='ram',
            name='percent_used',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='ram',
            name='used',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100000000)]),
        ),
    ]
